<a href="https://colab.research.google.com/github/juturpraveen/NLP/blob/master/HMM_Forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [0]:
states ={0:'H',1:'C'}
obs = {0:1, 1:2, 2:3}
obs_seq = np.array([3,1,3])
emi = np.array([[0.2, 0.4, 0.4],
                [0.5, 0.4, 0.1]])
pie = np.array([0.8, 0.2])
trans = np.array([[0.6, 0.4],
                  [0.5, 0.5]])

In [126]:
obs['3']

2

In [127]:
obs_seq.shape[0]
emi.shape[0]

2

In [0]:
def initialize_trellis(states, obs_seq):
  return torch.zeros(states, obs_seq)

In [0]:
trellis = initialize_trellis(emi.shape[0], obs_seq[0])

In [0]:
def emission_prob(obs, state):
  state_ind = states[state]
  obs_ind = obs[obs]
  return emi[(state_ind, obs_ind)]

In [139]:
emission_prob('3', 'H')

TypeError: ignored

In [109]:
a = 1
b = 2
print(emi[a,b])

0.1


In [27]:
print(trellis)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [0]:
#initialization
trellis[0,0] = pie[0] * emi[0,2]
trellis[1,0] = pie[1] * emi[1,2]

In [67]:
trellis

tensor([[0.3200, 0.0404, 0.0235],
        [0.0200, 0.0690, 0.0051]])

In [0]:
#recursion 1
trellis[0,1] = trellis[0,0] * trans[0,0] * emi[0,0] + trellis[1,0] * trans[1,0] * emi[0, 0] #Hot
trellis[1,1] = trellis[0,0] * trans[0,1] * emi[1,0] + trellis[1,0] * trans[1,1] * emi[1, 0] #Cold

In [63]:
trellis

tensor([[0.3200, 0.0404, 0.0000],
        [0.0200, 0.0690, 0.0000]])

In [0]:
#recursion 2
trellis[0,2] = trellis[0,1] * trans[0,0] * emi[0,2] + trellis[1,1] * trans[1,0] * emi[0,2]    #Hot
trellis[1,2] = trellis[0,1] * trans[0,1] * emi[1,2] + trellis[1,1] * trans[1,1] * emi[1,2]   #Cold

In [65]:
trellis

tensor([[0.3200, 0.0404, 0.0235],
        [0.0200, 0.0690, 0.0051]])

In [68]:
torch.tensor(emi)

tensor([[0.2000, 0.4000, 0.4000],
        [0.5000, 0.4000, 0.1000]], dtype=torch.float64)

In [0]:
states = {'H':0, 'C':1}
obs = {1:0, 2:1, 3:2}
obs_seq = np.array([3,1,3])
emi = np.array([[0.2, 0.4, 0.4],
                [0.5, 0.4, 0.1]])
pie = np.array([0.8, 0.2])
trans = np.array([[0.6, 0.4],
                  [0.5, 0.5]])

In [0]:
def return_emi(state, obsid):
  return emi[states[state.upper()], obs[obsid]]

In [0]:
def return_trans(prev_state, curr_state):
  prev = states[prev_state.upper()]
  curr = states[curr_state.upper()]
  return trans[prev, curr]

In [207]:
a = 'h'
a.upper()

'H'

In [208]:
return_trans('h','H')

0.6